### ISSUE TITLE
Fatal Error at news edit in default home template

### ISSUE THREAD

**Issue by timruether** [fraym/fraym#5]
After saving an edited news from default template home page, following error message is shown:

Fatal error: Call to undefined method Extension\News\Entity\News::getId() in /var/www/web2/web/Vendor/Gedmo/Translatable/TranslatableListener.php on line 747

**Comment by do-web** [comment]
What is the default language? I tried with this: Install -> Default Lang. Englisch -> After install -> Editing a News Entry -> No Error.

Have you some steps to reproduce this error?
